spring.application.name=leagueManager
spring.datasource.url=jdbc:postgresql://localhost:5432/leagueManager

spring.datasource.username=postgres
spring.datasource.password=admin
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
logging.level.org.springframework.data.jpa: trace
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.driverClassName=org.postgresql.Driver